Update umn-mkdocs.yml

diff --git a/mkdocs/umn-mkdocs.yml b/mkdocs/umn-mkdocs.yml
--- a/mkdocs/umn-mkdocs.yml
+++ b/mkdocs/umn-mkdocs.yml
@@ -50,12 +50,12 @@ jobs:
     - bash: |
         echo "##vso[task.setvariable variable=templateDocsPath;isreadonly=true]${{ parameters.DocsPath }}"
         echo "##vso[task.setvariable variable=templateArtifactName;isreadonly=true]${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}"
-  - bash: |
-      echo '${{ coalesce(parameters.DocsPath, variables['Build.DefinitionName']) }}'
-      echo '$(Build.DefinitionName)'
-      echo '${{ parameters.DocsPath }}'
-      if [[ '${{ parameters.DocsPath }}' == *"DocsPath"* ]]; then exit 1; fi;
-    displayName: Fail build if DocsPath is not set
+  # - bash: |
+  #     echo '${{ coalesce(parameters.DocsPath, variables['Build.DefinitionName']) }}'
+  #     echo '$(Build.DefinitionName)'
+  #     echo '${{ parameters.DocsPath }}'
+  #     if [[ '${{ parameters.DocsPath }}' == *"DocsPath"* ]]; then exit 1; fi;
+  #   displayName: Fail build if DocsPath is not set
   # - script: |
   #     sudo npm i -g markdownlint-cli
   #     markdownlint "**/*.md"
@@ -80,25 +80,25 @@ jobs:
       mkdocs build -d $(Build.ArtifactStagingDirectory)
     displayName: mkdocs-material build
   - publish: $(Build.ArtifactStagingDirectory)
-    artifact: ${{ variables.templateArtifactName }}
+    artifact: $(templateArtifactName)
 - template: deploy-docs.yml
   parameters:
-    DocsPath: ${{ variables.templateDocsPath }}
+    DocsPath: $(templateDocsPath)
     CleanDestination: ${{ parameters.CleanDestination }}
-    ArtifactName: ${{ variables.templateArtifactName }}
+    ArtifactName: $(templateArtifactName)
     Environment: Dev
     BuildCondition: and(succeeded(), eq(${{ parameters.DevDeploys }}, true), startsWith(variables['build.sourceBranchName'], 'dev'))
 - template: deploy-docs.yml
   parameters:
-    DocsPath: ${{ variables.templateDocsPath }}
+    DocsPath: $(templateDocsPath)
     CleanDestination: ${{ parameters.CleanDestination }}
-    ArtifactName: ${{ variables.templateArtifactName }}
+    ArtifactName: $(templateArtifactName)
     Environment: Tst
     BuildCondition: or(and(succeeded(), not(startsWith(variables['build.sourceBranchName'], 'dev')), eq(${{ parameters.DevDeploys }}, true)), and(succeeded(), eq(${{ parameters.DevDeploys }}, false)))
 - template: deploy-docs.yml
   parameters:
-    DocsPath: ${{ variables.templateDocsPath }}
+    DocsPath: $(templateDocsPath)
     CleanDestination: ${{ parameters.CleanDestination }}
-    ArtifactName: ${{ variables.templateArtifactName }}
+    ArtifactName: $(templateArtifactName)
     Environment: Prd
     BuildCondition: and(succeeded(), eq(variables['build.sourceBranchName'], '${{ parameters.DefaultBranch }}'))
